routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/register', function() {
	return redirect(route('login'));
})->name('home');

Route::get('/', function() {
	return redirect(route('home'));
})->name('home');

Route::get('/validar/{token}', 'UsuariosController@validar')->name('registro');

/* Para acceder a este middleware deben estar logueados */
Route::group(['middleware' => ['web','auth']], function () {
	Route::get('/inicio', 'HomeController@index')->name('home');
	Route::get('/salir', 'HomeController@salir')->name('salir');
	Route::get('/perfil', 'UsuariosController@perfil')->name('perfil');
	Route::post('/perfil/{id}/update_perfil', 'UsuariosController@update_perfil')->name('update_perfil');

	/* Solo super administradores */
	// Route::group(['middleware' => ['administrador','empresa']], function () {
		Route::resource('empresas', 'EmpresasController');
		Route::get('empresas/estado/{id}', 'EmpresasController@estado')->name('empresa_estado');
		Route::get('empresas/{id}/usuarios', 'EmpresasController@usuarios')->name('empresa_usuarios');

		Route::resource('usuarios', 'UsuariosController');
		Route::get('usuarios/estado/{id}', 'UsuariosController@estado')->name('usuario_estado');
		Route::get('usuarios/{id}/enviar_invitacion', 'UsuariosController@enviar_invitacion_url')->name('enviar_invitacion');
		Route::post('usuarios/{id}/validar_update', 'UsuariosController@validar_update')->name('validar_update');

		Route::resource('proyectos', 'ProyectosController');
		
		Route::resource('formularios', 'FormulariosController');
		Route::get('formularios/{id}/formulario', 'FormulariosController@get_formulario')->name('formulario_cuerpo');
	// });
});

app/Proyecto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
	protected $table = "proyectos";
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Proyecto;
use App\User;
use App\Formulario;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proyectos = Proyecto::get();
        return view('proyecto.index',compact('proyectos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $usuarios = User::get();
        $formularios = Formulario::get();
        $supervisores = collect([]);
        foreach ($usuarios as $usuario) {
            if ($usuario->rol->nombre == "Supervisor") {
                $supervisores->push($usuario);
            }
        }

        return view('proyecto.create',compact("supervisores","formularios"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/proyecto/create.blade.php
@extends('layouts.app')

@section('titulo')
Crear formulario
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                    <a href="{{ route('usuarios.index') }}"><p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Formularios&nbsp;/&nbsp;</p></a>
                    <p class="text-primary mb-0 hover-cursor">Crear formulario</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('proyectos.store') }}">
                    @csrf

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <input id="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('nombre') }}" required autocomplete="nombre" autofocus>

                                @error('nombre')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="estado" class="col-md-4 col-form-label text-md-right">Estado</label>

                                <select id="estado" type="text" class="form-control @error('estado') is-invalid @enderror" name="estado" required autofocus>
                                    <option value="0">Inactivo</option>
                                    <option value="1">Activo</option>
                                </select>

                                @error('estado')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="rol">Supervisor</label>
                                <select class="form-control" id="supervisor" name="supervisor" required>
                                    <option value="" selected>Seleccione un supervisor</option>

                                    @foreach ($supervisores as $supervisor)
                                    <option value="{!! $supervisor->id !!}" {!! old('supervisor') == $supervisor->id ? 'selected' : '' !!}>{!! $supervisor->nombre !!}</option>
                                    @endforeach

                                </select>

                                @error('supervisor')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="rol">Formulario</label>
                                
                                <div class="input-group">
                                    <select class="form-control" id="formulario" name="formulario" required>
                                        <option value="" selected>Seleccione un formulario</option>

                                        @foreach ($formularios as $formulario)
                                        <option value="{!! $formulario->id !!}" {!! old('formulario') == $formulario->id ? 'selected' : '' !!}>{!! $formulario->nombre !!}</option>
                                        @endforeach

                                    </select>

                                    <div class="input-group-append">
                                        <button class="btn btn-sm btn-primary" id="mostrar_formulario" type="button">Ver</button>
                                    </div>
                                </div>

                                @error('formulario')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="form-group row mt-2 mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="button" class="btn btn-primary submit_class">
                                Crear
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
<script>

    jQuery(function($) {
        $('#mostrar_formulario').on('click', function(event) {
            let formulario = $('#formulario');
            let formulario_id = formulario.val();

            if (formulario_id == '') {
                Swal.fire(
                  'Cuidado!',
                  'Para obtener una vista previa debes elegir un formulario!',
                  'warning'
                  );

                return false;
            }

            let _url = '{{ route('formulario_cuerpo','xxxx') }}';
            let url = _url.replace('xxxx', formulario_id);

            $.ajax({
                url: url,
                type: 'GET',
            })
            .done(function(res) {
                console.log(res);
            });
            
        });
    });

</script>
@endsection

resources/views/proyecto/index.blade.php
@extends('layouts.app')

@section('titulo')
Proyectos
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor">&nbsp;/&nbsp;</i></a>
                    <p class="text-primary mb-0 hover-cursor">Proyectos</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-end flex-wrap">
                <button type="button" onclick="location.href='{{ route('proyectos.create') }}';" class="btn btn-primary mt-2 mt-xl-0">Crear proyecto</button>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Listado de proyectos</p>
                <div class="table-responsive">
                    <table id="recent-purchases-listing" class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Fecha de creación</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($proyectos as $proyecto)
                            <tr>
                                <td>{!! $proyecto->nombre !!}</td>
                                <td>{!! $proyecto->email !!}</td>
                                <td>
                                    {!! $proyecto->activo == 'si' ? 'Activo' : 'Inactivo' !!}
                                </td>
                                <td>
                                    <div class="btn-group col-sm">

                                        <button class="btn btn-xs btn-info" type="button" onclick="location.href='{{ route('usuarios.edit',$proyecto->id) }}';" title="Editar empresa."><i class="mdi mdi-grease-pencil"></i></button>

                                        @if ($proyecto->activo == 'no')
                                        
                                        {{----}}<button class="btn btn-xs btn-success" onclick="location.href='{{ route('usuario_estado',$proyecto->id) }}';" title="Habilitar empresa"><i class="mdi mdi-check"></i></button>
                                        
                                        @else
                                        
                                        {{----}}<button class="btn btn-xs btn-danger" onclick="location.href='{{ route('usuario_estado',$proyecto->id) }}';" title="Inhabilitar empresa"><i class="mdi mdi-close"></i></button>
                                        
                                        @endif

                                    </div>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function() {
        $('#recent-purchases-listing').DataTable({
            "language": {
                search: "Buscar"
            },
            paging: false, info: false
        });
    });
</script>
@endsection