routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/register', function() {
	return redirect(route('login'));
})->name('home');

Route::get('/', function() {
	return redirect(route('home'));
})->name('home');

Route::get('/validar/{token}', 'UsuariosController@validar')->name('registro');

/* Para acceder a este middleware deben estar logueados */
Route::group(['middleware' => ['web','auth']], function () {
	Route::get('/inicio', 'HomeController@index')->name('home');
	Route::get('/salir', 'HomeController@salir')->name('salir');
	Route::get('/perfil', 'UsuariosController@perfil')->name('perfil');
	Route::post('/perfil/{id}/update_perfil', 'UsuariosController@update_perfil')->name('update_perfil');

	/* Solo super administradores */
	// Route::group(['middleware' => ['administrador','empresa']], function () {
		Route::resource('empresas', 'EmpresasController');
		Route::get('empresas/estado/{id}', 'EmpresasController@estado')->name('empresa_estado');
		Route::get('empresas/{id}/usuarios', 'EmpresasController@usuarios')->name('empresa_usuarios');

		Route::resource('usuarios', 'UsuariosController');
		Route::get('usuarios/estado/{id}', 'UsuariosController@estado')->name('usuario_estado');
		Route::get('usuarios/{id}/enviar_invitacion', 'UsuariosController@enviar_invitacion_url')->name('enviar_invitacion');
		Route::post('usuarios/{id}/validar_update', 'UsuariosController@validar_update')->name('validar_update');

		Route::resource('proyectos', 'ProyectosController');
		
		Route::resource('formularios', 'FormulariosController');
		Route::get('formularios/{id}/formulario', 'FormulariosController@get_formulario')->name('formulario_cuerpo');
	// });
});

app/Empresa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
	protected $table = "empresas";
	public $timestamps = false;
	
	protected $fillable = ['activo'];
}

app/Http/Controllers/EmpresasController.php
<?php

namespace App\Http\Controllers;

use App\Empresa;
use App\User;
use Illuminate\Http\Request;

class EmpresasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empresas = Empresa::get();
        $usuarios = User::whereNotNull('empresas_id')->get();
        return view('empresa.index',compact('empresas','usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empresa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $nit = $request->nit;
        $nombre = $request->nombre;
        $activo = $request->activo;
        $email = $request->email;

        $empresa = new Empresa();
        $empresa->nit = $nit;
        $empresa->nombre = $nombre;
        $empresa->activo = $activo;
        $empresa->email = $email;

        $empresa->save();
        return redirect(route('empresas.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empresa = Empresa::findOrFail($id);
        return view('empresa.edit',compact('empresa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nit = $request->nit;
        $nombre = $request->nombre;
        $activo = $request->activo;
        $email = $request->email;

        $empresa = Empresa::findOrFail($id);
        $empresa->nit = $nit;
        $empresa->nombre = $nombre;
        $empresa->activo = $activo;
        $empresa->email = $email;

        $empresa->save();
        return redirect(route('empresas.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function estado(Request $request,$id)
    {
        $empresa = Empresa::findOrFail($id);
        $estado = 'si';
        
        if ($empresa->activo == 'si') {
            $estado = 'no';
        }

        $empresa->update(['activo' => $estado]);

        return redirect(route('empresas.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function usuarios($id)
    {
        $empresa = Empresa::findOrFail($id);
        $usuarios = User::where('empresas_id',$id)->get();

        return view('empresa.usuarios',compact('empresa','usuarios'));
    }
}

resources/views/empresa/create.blade.php
@extends('layouts.app')

@section('titulo')
Crear empresa
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                    <a href="{{ route('empresas.index') }}"><p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Empresas&nbsp;/&nbsp;</p></a>
                    <p class="text-primary mb-0 hover-cursor">Crear empresa</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Información general de la empresa</h4>
                <form method="POST" action="{{ route('empresas.store') }}">
                    @csrf

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nit">Nit</label>
                                <input type="text" class="form-control" id="nit" name="nit" value="" placeholder="Nit">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre">Nombre</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" value="" placeholder="Nombre completo">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Correo electronico</label>
                                <input type="email" class="form-control" id="email" name="email" value="" placeholder="Correo electronico">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="activo">Estado</label>
                                <select class="form-control" id="activo" name="activo">
                                    <option value="si">Activo</option>
                                    <option value="no">Inactivo</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="btn-group">
                        <button type="button" onclick="location.href='{{ route('empresas.index') }}';" class="btn btn-secondary">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Crear empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/empresa/edit.blade.php
@extends('layouts.app')

@section('titulo')
Crear empresa
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                    <a href="{{ route('empresas.index') }}"><p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Empresas&nbsp;/&nbsp;</p></a>
                    <p class="text-primary mb-0 hover-cursor">Editar empresa</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Información general de la empresa</h4>
                <form id="form_forms" method="POST" action="{{ route('empresas.update',$empresa->id) }}">
                    @csrf
                    {{ method_field('PATCH') }}

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nit">Nit</label>
                                <input type="text" class="form-control" id="nit" name="nit" value="{!! $empresa->nit !!}" placeholder="Nit">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre">Nombre</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" value="{!! $empresa->nombre !!}" placeholder="Nombre completo">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Correo electronico</label>
                                <input type="email" class="form-control" id="email" name="email" value="{!! $empresa->email !!}" placeholder="Correo electronico">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="activo">Estado</label>
                                <select class="form-control" id="activo" name="activo">
                                    <option {!! $empresa->activo == 'si' ? 'selected' : '' !!} value="si">Activo</option>
                                    <option {!! $empresa->activo == 'no' ? 'selected' : '' !!} value="no">Inactivo</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="btn-group">
                        <button type="button" onclick="location.href='{{ route('empresas.index') }}';" class="btn btn-secondary">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Actualizar empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/empresa/index.blade.php
@extends('layouts.app')

@section('titulo')
Inicio
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="mr-md-3 mr-xl-5">
                    <h2>Gestión de empresas</h2>

                    <div class="d-flex">
                        <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Empresas&nbsp;/&nbsp;</p>
                    </div>
                </div>

            </div>
            <div class="d-flex justify-content-between align-items-end flex-wrap">
                <button type="button" onclick="location.href='{{ route('empresas.create') }}';" class="btn btn-primary mt-2 mt-xl-0">Crear empresa</button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body dashboard-tabs p-0">
                <div class="tab-content py-0 px-0">
                    <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
                        <div class="d-flex flex-wrap justify-content-xl-between">
                            <div class="d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item">
                                <i class="mdi mdi mdi-counter mr-3 icon-lg text-danger"></i>
                                <div class="d-flex flex-column justify-content-around">
                                    <small class="mb-1 text-muted">Cantidad de empresas creadas</small>
                                    <h5 class="mr-2 mb-0">{{ $empresas->count() }}</h5>
                                </div>
                            </div>
                            <div class="d-flex border-md-right flex-grow-1 align-items-center justify-content-center p-3 item">
                                <i class="mdi mdi mdi-account mr-3 icon-lg text-success"></i>
                                <div class="d-flex flex-column justify-content-around">
                                    <small class="mb-1 text-muted">Cantidad de usuarios en empresas</small>
                                    <h5 class="mr-2 mb-0">{!! $usuarios->count() !!}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Listado de empresas</p>
                <div class="table-responsive">
                    <table id="recent-purchases-listing" class="table">
                        <thead>
                            <tr>
                                <th>Nit</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($empresas as $empresa)
                            <tr>
                                <td>{!! $empresa->nit !!}</td>
                                <td>{!! $empresa->nombre !!}</td>
                                <td>{!! $empresa->email !!}</td>
                                <td>{!! $empresa->activo == 'si' ? 'Activo' : 'Inactivo' !!}</td>
                                <td>
                                    <div class="btn-group col-sm">
                                        <button class="btn btn-xs btn-info" type="button" onclick="location.href='{{ route('empresas.edit',$empresa->id) }}';" title="Editar empresa."><i class="mdi mdi-grease-pencil"></i></button>
                                        
                                        @if ($empresa->activo == 'no')
                                        
                                        <button class="btn btn-xs btn-success" onclick="location.href='{{ route('empresa_estado',$empresa->id) }}';" title="Habilitar empresa"><i class="mdi mdi-check"></i></button>
                                        
                                        @else
                                        
                                        <button class="btn btn-xs btn-primary" type="button" onclick="location.href='{{ route('empresa_usuarios',$empresa->id) }}';" title="Ver usuarios."><i class="mdi mdi-account-multiple"></i></button>
                                        <button class="btn btn-xs btn-danger" onclick="location.href='{{ route('empresa_estado',$empresa->id) }}';" title="Inhabilitar empresa"><i class="mdi mdi-close"></i></button>
                                        
                                        @endif

                                    </div>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function() {
        $('#recent-purchases-listing').DataTable({
            "language": {
                search: "Buscar"
            },
            paging: false, info: false
        });
    });
</script>
@endsection

resources/views/empresa/usuarios.blade.php
@extends('layouts.app')

@section('titulo')
Usuarios de empresa
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                    <a href="{{ route('empresas.index') }}"><p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Empresas&nbsp;/&nbsp;</p></a>
                    <p class="text-muted mb-0 hover-cursor">[ {!! $empresa->nombre !!} ]&nbsp;/&nbsp;</p>
                    <p class="text-primary mb-0 hover-cursor">Usuarios por empresa</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-end flex-wrap">
                <button type="button" onclick="location.href='{{ route('empresas.index') }}';" class="btn btn-secondary mt-2 mt-xl-0">Volver</button>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Listado de usuarios</p>
                <div class="table-responsive">
                    <table id="recent-purchases-listing" class="table">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombre</th>
                                <th>Correo electronico</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($usuarios as $usuario)
                            <tr>
                                <td>{!! $usuario->usuario !!}</td>
                                <td>{!! $usuario->nombre !!}</td>
                                <td>{!! $usuario->email !!}</td>
                                <td>{!! $usuario->activo == 'si' ? 'Activo' : 'Inactivo' !!}</td>
                                <td>
                                    <div class="btn-group col-sm">
                                        <button class="btn btn-xs btn-info" type="button" onclick="location.href='{{ route('empresas.edit',$usuario->id) }}';" title="Editar empresa."><i class="mdi mdi-grease-pencil"></i></button>
                                        
                                        @if ($usuario->activo == 'no')
                                        
                                        <button class="btn btn-xs btn-success" onclick="location.href='{{ route('empresa_estado',$usuario->id) }}';" title="Habilitar empresa"><i class="mdi mdi-check"></i></button>
                                        
                                        @else
                                        
                                        <button class="btn btn-xs btn-danger" onclick="location.href='{{ route('empresa_estado',$usuario->id) }}';" title="Inhabilitar empresa"><i class="mdi mdi-close"></i></button>
                                        
                                        @endif

                                    </div>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function() {
        $('#recent-purchases-listing').DataTable({
            "language": {
                search: "Buscar"
            },
            paging: false, info: false
        });
    });
</script>
@endsection