routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/register', function() {
	return redirect(route('login'));
})->name('home');

Route::get('/', function() {
	return redirect(route('home'));
})->name('home');

Route::get('/validar/{token}', 'UsuariosController@validar')->name('registro');

/* Para acceder a este middleware deben estar logueados */
Route::group(['middleware' => ['web','auth']], function () {
	Route::get('/inicio', 'HomeController@index')->name('home');
	Route::get('/salir', 'HomeController@salir')->name('salir');
	Route::get('/perfil', 'UsuariosController@perfil')->name('perfil');
	Route::post('/perfil/{id}/update_perfil', 'UsuariosController@update_perfil')->name('update_perfil');

	/* Solo super administradores */
	// Route::group(['middleware' => ['administrador','empresa']], function () {
		Route::resource('empresas', 'EmpresasController');
		Route::get('empresas/estado/{id}', 'EmpresasController@estado')->name('empresa_estado');
		Route::get('empresas/{id}/usuarios', 'EmpresasController@usuarios')->name('empresa_usuarios');

		Route::resource('usuarios', 'UsuariosController');
		Route::get('usuarios/estado/{id}', 'UsuariosController@estado')->name('usuario_estado');
		Route::get('usuarios/{id}/enviar_invitacion', 'UsuariosController@enviar_invitacion_url')->name('enviar_invitacion');
		Route::post('usuarios/{id}/validar_update', 'UsuariosController@validar_update')->name('validar_update');

		Route::resource('proyectos', 'ProyectosController');
		
		Route::resource('formularios', 'FormulariosController');
		Route::get('formularios/{id}/formulario', 'FormulariosController@get_formulario')->name('formulario_cuerpo');
	// });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <title>Auditorias - @yield('titulo')</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ asset('admin/plugins/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/base/vendor.bundle.base.css') }}">        
    <link rel="stylesheet" href="{{ asset('admin/plugins/datatables.net-bs4/dataTables.bootstrap4.css') }}">        
    <link rel="stylesheet" href="{{ asset('admin/css/style.css') }}">

    <link rel="shortcut icon" href="{{ asset('admin/images/favicon.png') }}" />
    @yield('styles')
</head>
<body>
    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">  
                    <a class="navbar-brand brand-logo" href="{{ route('home') }}">
                        {{-- <img src="{{ asset('admin/images/logo.svg') }}" alt="logo"/> --}}
                        Auditorias
                    </a>

                    <a class="navbar-brand brand-logo-mini" href="{{ route('home') }}">
                        {{-- <img src="{{ asset('admin/images/logo-mini.svg') }}" alt="logo"/> --}}
                        A
                    </a>

                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>  
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            {{-- <img src="{{ asset('admin/images/faces/face5.jpg') }}" alt="profile"/> --}}
                            <span class="nav-profile-name">{!! Auth::user()->nombre !!}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            
                            @if(Auth::user()->inv_activa == 'no')
                            <a class="dropdown-item" href="{{ route('perfil') }}">
                                <i class="mdi mdi-settings text-primary"></i>
                                Mi perfil
                            </a>
                            @endif

                            <a href="{{ route('salir') }}" class="dropdown-item">
                                <i class="mdi mdi-logout text-primary"></i>
                                Cerrar sesión
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('home') }}">
                            <i class="mdi mdi-home menu-icon"></i>
                            <span class="menu-title">Inicio</span>
                        </a>
                    </li>

                    @if(Auth::user()->rol->nombre == 'Super Administrador')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('empresas.index') }}">
                            <i class="mdi mdi-desktop-tower menu-icon"></i>
                            <span class="menu-title">Empresas</span>
                        </a>
                    </li>
                    @endif

                    @if(Auth::user()->rol->nombre == 'Super Administrador' || Auth::user()->rol->nombre == 'Administrador')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('usuarios.index') }}">
                            <i class="mdi mdi-account-multiple menu-icon"></i>
                            <span class="menu-title">Usuarios</span>
                        </a>
                    </li>
                    @endif


                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('formularios.index') }}">
                            <i class="mdi mdi-file-document menu-icon"></i>
                            <span class="menu-title">Formularios</span>
                        </a>
                    </li>
                   
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('proyectos.index') }}">
                            <i class="mdi mdi-folder-multiple-outline menu-icon"></i>
                            <span class="menu-title">Proyectos</span>
                        </a>
                    </li>
                    
                </ul>
            </nav>

            <div class="main-panel">
                <div class="content-wrapper">

                    @yield('contenido')
                </div>

                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © {{ date('Y') }}. All rights reserved.</span>
                    </div>
                </footer>
            </div>

        </div>
    </div>

    <script src="{{ asset('admin/plugins/base/vendor.bundle.base.js') }}"></script>
    <script src="{{ asset('admin/plugins/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables.net/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/plugins/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('admin/js/off-canvas.js') }}"></script>
    <script src="{{ asset('admin/js/hoverable-collapse.js') }}"></script>
    <script src="{{ asset('admin/js/template.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    
    @include('layouts.nswal')

    <script src="{{ asset('admin/js/dashboard.js') }}"></script>
    <script src="{{ asset('admin/js/data-table.js') }}"></script>
    <script src="{{ asset('admin/js/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/js/dataTables.bootstrap4.js') }}"></script>
    @yield('scripts')
</body>

</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Auditorias - @yield('tipo')</title>
    <link rel="stylesheet" href="{{ asset('admin/plugins/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/base/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/css/style.css') }}">
    <link rel="shortcut icon" href="{{ asset('admin/images/favicon.png') }}" />
</head>

<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">

                            @yield('contenido')

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('admin/plugins/base/vendor.bundle.base.js') }}"></script>
    <script src="{{ asset('admin/js/off-canvas.js') }}"></script>
    <script src="{{ asset('admin/js/hoverable-collapse.js') }}"></script>
    <script src="{{ asset('admin/js/template.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    @include('layouts.nswal')
</body>

</html>

resources/views/layouts/email.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="format-detection" content="date=no" />
	<meta name="format-detection" content="address=no" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="x-apple-disable-message-reformatting" />
	<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i" rel="stylesheet" />
	<title>Auditorias</title>


	<style type="text/css" media="screen">
		/* Linked Styles */
		body { padding:0 !important; margin:0 !important; display:block !important; min-width:100% !important; width:100% !important; background:#f4f4f4; -webkit-text-size-adjust:none }
		a { color:#777777; text-decoration:none }
		p { padding:0 !important; margin:0 !important } 
		img { -ms-interpolation-mode: bicubic; }

		.mcnPreviewText { display: none !important; }
		.cke_editable,
		.cke_editable a,
		.cke_editable span,
		.cke_editable a span { color: #000001 !important; }

		/* Mobile styles */
		@media only screen and (max-device-width: 480px), only screen and (max-width: 480px) {
			.mobile-shell { width: 100% !important; min-width: 100% !important; }
			.bg { background-size: 100% auto !important; -webkit-background-size: 100% auto !important; }

			.text-header,
			.m-center { text-align: center !important; }

			.center { margin: 0 auto !important; }
			.container { padding: 20px 10px !important }

			.td { width: 100% !important; min-width: 100% !important; }

			.m-br-15 { height: 15px !important; }
			.p30-15 { padding: 30px 15px !important; }
			.p0-15-30 { padding: 0px 15px 30px 15px !important; }
			.p0-15 { padding: 0px 15px !important; }
			.pt0 { padding-top: 0px !important; }
			.mpb30 { padding-bottom: 30px !important; }
			.mpb15 { padding-bottom: 15px !important; }

			.m-td,
			.m-hide { display: none !important; width: 0 !important; height: 0 !important; font-size: 0 !important; line-height: 0 !important; min-height: 0 !important; }

			.m-block { display: block !important; }

			.fluid-img img { width: 100% !important; max-width: 100% !important; height: auto !important; }

			.column,
			.column-dir,
			.column-top,
			.column-empty,
			.column-empty2,
			.column-dir-top { float: left !important; width: 100% !important; display: block !important; }

			.column-empty { padding-bottom: 30px !important; }
			.column-empty2 { padding-bottom: 10px !important; }

			.content-spacing { width: 15px !important; }
		}
	</style>
</head>
<body class="body" style="padding:0 !important; margin:0 !important; display:block !important; min-width:100% !important; width:100% !important; background:#f4f4f4; -webkit-text-size-adjust:none;">
	<!--*|IF:MC_PREVIEW_TEXT|*-->
	<!--[if !gte mso 9]><!-->
	<span class="mcnPreviewText" style="display:none; font-size:0px; line-height:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility:hidden; mso-hide:all;">*|MC_PREVIEW_TEXT|*</span>
	<!--<![endif]-->
	<!--*|END:IF|*-->
	<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f4f4f4">
		<tr>
			<td align="center" valign="top">
				<!-- Header -->
				<table width="100%" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td align="center" class="p30-15" style="padding: 30px;">
							<table width="650" border="0" cellspacing="0" cellpadding="0" class="mobile-shell">
								<tr>
									<td class="td" style="width:650px; min-width:650px; font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;">
										<!-- Header -->
										<table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<th class="column" width="145" style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;">
													<table width="100%" border="0" cellspacing="0" cellpadding="0">
														<tr>
															<td class="img m-center" style="font-size:30pt; line-height:0pt; text-align:left; color: black;">
																<!-- <img src="images/t7_logo.jpg" width="106" height="37" mc:edit="image_1" style="max-width:106px;" border="0" alt="" /> -->
																<strong>Auditorias</strong>
															</td>
														</tr>
													</table>
												</th>
												<th class="column-empty2" width="1" style="font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal; vertical-align:top;"></th>
											</tr>
										</table>
										<!-- END Header -->
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				<!-- END Header -->

				<!-- Intro -->
				<div mc:repeatable="Select" mc:variant="Intro">
					<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f4f4f4">
						<tr>
							<td align="center">
								<table width="650" border="0" cellspacing="0" cellpadding="0" class="mobile-shell">
									<tr>
										<td class="td" style="width:650px; min-width:650px; font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;">
											<table width="100%" border="0" cellspacing="0" cellpadding="0">
												<tr>
													<!-- <td class="fluid-img" style="border-bottom: 7px solid #00a2ff; font-size:0pt; line-height:0pt; text-align:left;"><img src="images/t7_image1.jpg" width="650" height="366" mc:edit="image_2" style="max-width:650px;" border="0" alt="" /></td> -->
												</tr>
												<tr>
													<td class="bbrr" bgcolor="#f4f4f4" style="border-radius:0px 0px 12px 12px;">
														<table width="100%" border="0" cellspacing="0" cellpadding="0">
															<tr>
																<td class="p30-15" style="padding: 50px 30px 60px 30px;">
																	<table width="100%" border="0" cellspacing="0" cellpadding="0">
																		<tr>
																			<td class="h3 center pb25" style="color:#000000; font-family:'Lato', Arial ,sans-serif; font-size:24px; line-height:32px; font-weight:bold; text-align:center; padding-bottom:25px;"><div mc:edit="text_2">{!! $titulo !!}</div></td>
																		</tr>
																		<tr>
																			<td class="text-center pb25" style="color:#777777; font-family:'Lato', Arial,sans-serif; font-size:17px; line-height:30px; text-align:center; padding-bottom:25px;"><div mc:edit="text_3">{!! $descripcion !!}</div></td>
																		</tr>
																		<!-- Button -->
																		<tr mc:hideable>
																			<td align="center">
																				<table class="center" border="0" cellspacing="0" cellpadding="0" style="text-align:center;">
																					<tr>
																						<td class="text-button" style="background:#1a5fff; color:#ffffff; font-family:Arial ,sans-serif; font-size:14px; line-height:18px; padding:12px 20px; text-align:center; text-transform:uppercase; font-weight:bold; border-radius:22px;"><div mc:edit="text_4"><a href="{!! $accion !!}" target="_blank" class="link-white" style="color:#ffffff; text-decoration:none;"><span class="link-white" style="color:#ffffff; text-decoration:none;">{!! $texto_boton !!}</span></a></div></td>
																					</tr>
																				</table>
																			</td>
																		</tr>
																		<!-- END Button -->
																	</table>
																</td>
															</tr>
														</table>
													</td>
												</tr>
											</table>
											<!-- END Intro -->
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
				<!-- END Intro -->

				<!-- Footer -->
				<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
					<tr>
						<td valign="top" align="center" class="p30-15" style="padding: 50px 0px 50px 0px;">
							<table width="650" border="0" cellspacing="0" cellpadding="0" class="mobile-shell">
								<tr>
									<td class="td" style="width:650px; min-width:650px; font-size:0pt; line-height:0pt; padding:0; margin:0; font-weight:normal;">
										<table width="100%" border="0" cellspacing="0" cellpadding="0">
											<tr>
												<td class="text-footer1 pb10" style="color:#999999; font-family:'Lato', Arial,sans-serif; font-size:14px; line-height:20px; text-align:center; padding-bottom:10px;"><div mc:edit="text_44">Auditorias</div></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				<!-- END Footer -->

			</td>
		</tr>
	</table>
</body>
</html>

resources/views/layouts/nswal.blade.php
@foreach (session('flash_notification', collect())->toArray() as $message)
<script type="text/javascript">
    Swal.fire({
      title: 'Notificación',
      text: "{!! $message['message'] !!}",
      type: "{!! $message['level'] !!}",
      confirmButtonText: "Cerrar"
  })
</script>
@endforeach

{{ session()->forget('flash_notification') }}