routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/register', function() {
	return redirect(route('login'));
})->name('home');

Route::get('/', function() {
	return redirect(route('home'));
})->name('home');

Route::get('/validar/{token}', 'UsuariosController@validar')->name('registro');

/* Para acceder a este middleware deben estar logueados */
Route::group(['middleware' => ['web','auth']], function () {
	Route::get('/inicio', 'HomeController@index')->name('home');
	Route::get('/salir', 'HomeController@salir')->name('salir');
	Route::get('/perfil', 'UsuariosController@perfil')->name('perfil');
	Route::post('/perfil/{id}/update_perfil', 'UsuariosController@update_perfil')->name('update_perfil');

	/* Solo super administradores */
	// Route::group(['middleware' => ['administrador','empresa']], function () {
		Route::resource('empresas', 'EmpresasController');
		Route::get('empresas/estado/{id}', 'EmpresasController@estado')->name('empresa_estado');
		Route::get('empresas/{id}/usuarios', 'EmpresasController@usuarios')->name('empresa_usuarios');

		Route::resource('usuarios', 'UsuariosController');
		Route::get('usuarios/estado/{id}', 'UsuariosController@estado')->name('usuario_estado');
		Route::get('usuarios/{id}/enviar_invitacion', 'UsuariosController@enviar_invitacion_url')->name('enviar_invitacion');
		Route::post('usuarios/{id}/validar_update', 'UsuariosController@validar_update')->name('validar_update');

		Route::resource('proyectos', 'ProyectosController');
		
		Route::resource('formularios', 'FormulariosController');
		Route::get('formularios/{id}/formulario', 'FormulariosController@get_formulario')->name('formulario_cuerpo');
	// });
});

app/Formulario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Formulario extends Model
{
    protected $table = "formularios";
}

app/Http/Controllers/FormulariosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Formulario;

use Auth;

class FormulariosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $formularios = Formulario::get();
        return view('formulario.index',compact('formularios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('formulario.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $estado = 'si';
        // $estado = $request->estado;


        $formulario = new Formulario();
        $formulario->creador_id = Auth::user()->id;
        $formulario->nombre = $request->nombre;
        $formulario->activo = $estado;
        $formulario->formulario = $request->arreglos_campos;

        $formulario->save();
        return redirect(route('formularios.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function get_formulario($id)
    {
        return Formulario::findOrFail($id)->formulario;
    }
}

resources/views/formulario/create.blade.php
@extends('layouts.app')

@section('titulo')
Crear formulario
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor"></i></a>
                    <a href="{{ route('usuarios.index') }}"><p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Formularios&nbsp;/&nbsp;</p></a>
                    <p class="text-primary mb-0 hover-cursor">Crear formulario</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form id="form_forms" method="POST" action="{{ route('formularios.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre" class="col-form-label text-md-right">{{ __('Name') }}</label>
                                <input id="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('nombre') }}" required autocomplete="nombre" autofocus>

                                @error('nombre')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="estado" class="col-form-label text-md-right">Estado</label>
                                <select id="estado" type="text" class="form-control @error('estado') is-invalid @enderror" name="estado" required autofocus>
                                    <option value="no">Inactivo</option>
                                    <option value="si" selected>Activo</option>
                                </select>

                                @error('estado')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <hr>
                    <div id="fb-editor"></div>
                    <hr>

                    <div class="form-group row mt-2 mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="button" class="btn btn-primary submit_class">
                                Crear
                            </button>
                        </div>
                    </div>

                    <input type="hidden" name="arreglos_campos" id="arreglos_campos">
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
<script>

    jQuery(function($) {
        let options = {
            showActionButtons: false,
        };

        let fb_ed = $(document.getElementById('fb-editor')).formBuilder(options);

        setTimeout(function() {
            fb_ed.actions.setLang('es-ES');
        }, 1000);

        $('.submit_class').on('click', function(event) {
            $("#arreglos_campos").val(JSON.stringify(fb_ed.actions.getData()));
            setTimeout(function() {
                $("#form_forms").submit();
            }, 200);
        });
    });

</script>
@endsection

resources/views/formulario/index.blade.php
@extends('layouts.app')

@section('titulo')
Formularios
@endsection

@section('contenido')
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="d-flex justify-content-between flex-wrap">
            <div class="d-flex align-items-end flex-wrap">
                <div class="d-flex">
                    <a href="{{ route('home') }}"><i class="mdi mdi-home text-muted hover-cursor">&nbsp;/&nbsp;</i></a>
                    <p class="text-primary mb-0 hover-cursor">Formularios</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-items-end flex-wrap">
                <button type="button" onclick="location.href='{{ route('formularios.create') }}';" class="btn btn-primary mt-2 mt-xl-0">Crear formulario</button>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-title">Listado de formularios</p>
                <div class="table-responsive">
                    <table id="recent-purchases-listing" class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Fecha de creación</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($formularios as $formulario)
                            <tr>
                                <td>{!! $formulario->nombre !!}</td>
                                <td>{!! $formulario->created_at->format('d-m-Y') !!}</td>
                                <td>
                                    {!! $formulario->activo == 'si' ? 'Activo' : 'Inactivo' !!}
                                </td>
                                <td>
                                    <div class="btn-group col-sm">

                                        <button class="btn btn-xs btn-primary" onclick="location.href='{{ route('usuario_estado',$formulario->id) }}';" title="Editar formulario"><i class="mdi mdi-pencil"></i></button>
                                        
                                        @if ($formulario->activo == 'no')
                                        
                                        {{----}}<button class="btn btn-xs btn-success" onclick="location.href='{{ route('usuario_estado',$formulario->id) }}';" title="Habilitar formulario"><i class="mdi mdi-check"></i></button>
                                        
                                        @else
                                        
                                        {{----}}<button class="btn btn-xs btn-danger" onclick="location.href='{{ route('usuario_estado',$formulario->id) }}';" title="Inhabilitar formulario"><i class="mdi mdi-close"></i></button>
                                        
                                        @endif

                                    </div>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function() {
        $('#recent-purchases-listing').DataTable({
            "language": {
                search: "Buscar"
            },
            paging: false, info: false
        });
    });
</script>
@endsection